extends SceneTree
const ContextType = preload("res://scripts/services/clan_service_context.gd")
const StateType = preload("res://scripts/data/clan_state.gd")
const Factory = preload("res://scripts/factory/creature_factory.gd")
const Pact = preload("res://scripts/services/pact_service.gd")
const Enums = preload("res://scripts/core/enums.gd")
const Campaign = preload("res://scripts/services/power_campaign_service.gd")
const Refuge = preload("res://scripts/services/refuge_service.gd")
func _init() -> void: call_deferred("_run")
func _run() -> void:
	var ctx := ContextType.new(StateType.new())
	for route in ["combat", "diplomatie", "occultisme", "liberation", "pacte", "alliance"]:
		var profile: Resource = Factory.new().create_from_dict({"id": route, "nom": "Test"})
		assert(ctx.creatures.add_available_creature(profile))
		assert(ctx.creatures.acquire_creature(profile, route).ok)
		assert(not ctx.creatures.acquire_creature(profile, route).ok)
		assert(ctx.creatures.get_profile_by_id(route).metadata.acquisition_route == route)
	assert(ctx.creatures.export_state().available.is_empty())
	var restored = load("res://scripts/services/creature_roster_service.gd").new()
	restored.import_state(ctx.creatures.export_state())
	assert(restored.get_captured_list().size() == 6)
	var pacts := Pact.new()
	var threshold := pacts.calculate_required_power("a", "hero", Enums.PactType.SERVICE)
	assert(threshold == pacts.calculate_pact_success_chance("a", "hero", Enums.PactType.SERVICE))
	pacts.offer_pact("a", "hero", Enums.PactType.SERVICE, {"ritual_power": threshold - 1})
	assert(not pacts.attempt_pact_ritual("a", "hero").ok)
	pacts.offer_pact("b", "hero", Enums.PactType.SERVICE, {"ritual_power": threshold})
	assert(pacts.attempt_pact_ritual("b", "hero").ok)
	var cm = root.get_node("ClanManager")
	cm.nouvelle_partie("Aren", "Échos", "hellcaster", {})
	Refuge.initialize(cm.service_context)
	Campaign.ensure(cm.service_context)
	assert(Campaign.execute(cm.service_context, "pact").accepted)
	assert(cm.get_creature_roster_service().get_profile_by_id("gallery_echo") != null)
	cm.sauvegarder()
	assert(cm.charger_sauvegarde())
	assert(cm.get_creature_roster_service().get_captured_list().size() == 1)
	assert(cm.campaign.get("run", {}).is_empty())
	print("CLAN_SECONDARY_SERVICES_OK")
	quit()
