extends SceneTree
const Refuge = preload("res://scripts/services/refuge_service.gd")
const Combat = preload("res://scripts/services/tactical_combat_service.gd")
var failures: Array[String] = []
func _init() -> void: call_deferred("run")
func check(value: bool, message: String) -> void:
	if not value: failures.append(message)
func run() -> void:
	var cm := root.get_node("ClanManager")
	var dungeon := root.get_node("DungeonGenerator")
	root.get_node("SaveSystem").set_active_slot("expedition_corruption_test")
	cm.nouvelle_partie("Aren", "Cendres", "hellcaster", {})
	Refuge.initialize(cm)
	var service = cm.get_corruption_service()
	check(service.has_character("hero") and service.has_character("pnj_kael"), "profils canoniques")
	check(not cm.apply_corruption("unknown", 10).ok, "personnage inconnu refusé")
	check(dungeon.start_expedition(["pnj_kael"]).is_empty(), "sortie préparée")
	dungeon.inspect_arrival("inscription")
	check(service.get_corruption_level("hero") == 0.0, "observer ne corrompt pas")
	dungeon.touch_inscription()
	check(service.get_corruption_level("hero") == 8.0, "résistance 50 % appliquée au contact")
	dungeon.touch_inscription()
	check(service.get_corruption_level("hero") == 8.0, "contact unique")
	cm.charger_sauvegarde()
	service = cm.get_corruption_service()
	dungeon.touch_inscription()
	check(service.get_corruption_level("hero") == 8.0, "contact non répété après chargement")
	dungeon.inspect_arrival("passage")
	dungeon.enter_dungeon()
	check(service.get_corruption_level("hero") == 12.0 and service.get_corruption_level("pnj_kael") == 4.0, "exposition équipe à l’entrée")
	var mana: int = cm.get_ressource("mana")
	check(not cm.purify_character("hero").ok and cm.get_ressource("mana") == mana, "pas de purification en sortie")
	var base_stats := JSON.stringify(cm.get_stats())
	for row in [[0.0,0], [19.9,0], [20.0,1], [40.0,2], [60.0,3], [80.0,4], [95.0,5], [100.0,5]]:
		service.set_level("hero", row[0])
		check(service.get_stage("hero") == row[1], "seuil %s" % row[0])
	service.set_level("hero", 1000.0)
	check(service.get_level("hero") == 100.0, "borne haute")
	service.set_level("hero", 60.0)
	dungeon.resolve_quiet_room()
	dungeon.advance_room()
	var battle: Dictionary = dungeon.ensure_battle()
	var hero: Dictionary = {}
	for unit in battle.units:
		if str(unit.id) == "hero": hero = unit
	check(int(hero.initiative) == maxi(0, cm.get_stat("espionnage") - 3), "malus initiative au combat")
	check(int(hero.magie) == maxi(0, cm.get_stat("magie") - 1), "malus magie au combat")
	check(int(hero.max_hp) == 18 + cm.get_stat("commandement") - 4, "malus PV maximum")
	check(JSON.stringify(cm.get_stats()) == base_stats, "stats de base intactes")
	var snapshot := JSON.stringify(battle)
	cm.sauvegarder()
	cm.charger_sauvegarde()
	check(JSON.parse_string(JSON.stringify(dungeon.ensure_battle())) == JSON.parse_string(snapshot), "malus non répété au chargement combat")
	dungeon.return_to_refuge()
	service = cm.get_corruption_service()
	mana = cm.get_ressource("mana")
	var food: int = cm.get_ressource("nourriture")
	var panel: Control = load("res://scripts/ui/refuge_panel.gd").new()
	root.add_child(panel)
	await process_frame
	var purify: Button
	for button in panel.find_children("*", "Button", true, false):
		if button.text.begins_with("Purifier Aren"): purify = button
	check(purify != null, "commande de purification visible")
	if purify: purify.pressed.emit()
	check(service.get_level("hero") == 50.0 and service.get_level("pnj_kael") == 4.0, "bouton purifie la bonne personne")
	panel.queue_free()
	await process_frame
	check(cm.get_ressource("mana") == mana - 4 and cm.get_ressource("nourriture") == food - 1, "coût purification")
	cm.charger_sauvegarde()
	service = cm.get_corruption_service()
	check(service.get_level("hero") == 50.0, "purification sauvegardée")
	cm.payer({"mana": cm.get_ressource("mana")})
	check(not cm.purify_character("hero").ok and service.get_level("hero") == 50.0, "coût insuffisant sans mutation")
	service.set_level("hero", -100.0)
	check(service.get_level("hero") == 0.0 and not cm.purify_character("hero").ok, "borne basse et purification inutile refusée")
	var path: String = root.get_node("SaveSystem").get_clan_save_path()
	var legacy := JsonPersistenceService.read_json_with_backup(path)
	legacy.erase("corruption_state")
	legacy.pnj_gestion.roster[0]["corruption"] = 12.0
	JsonPersistenceService.write_json_atomic(path, legacy)
	cm.charger_sauvegarde()
	check(cm.get_corruption_service().get_level("hero") == 0.0 and cm.get_corruption_service().get_level("pnj_kael") == 12.0, "migration ancienne sauvegarde")
	cm.nouvelle_partie("Autre", "Autre", "hellcaster", {})
	check(cm.get_corruption_service().get_level("hero") == 0.0, "nouvelle partie isolée")
	if failures.is_empty(): print("EXPEDITION_CORRUPTION_OK")
	else:
		for message in failures: push_error(message)
	quit(0 if failures.is_empty() else 1)
